[package]
name = "nolex"
version = "0.1.0"
authors = ["Minghao Liu <molikto@gmail.com>"]
edition = "2018"

[build-dependencies]
cc="*"

[dependencies]
druid = { git = "https://github.com/linebender/druid.git" }
tree-sitter = "0.16.1"
regex = "1"
